// File generated by FlutterFire CLI — replace via `flutterfire configure`.
// Placeholder values will NOT authenticate until you configure a real Firebase project.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Run from `frontend/job_tracker`:
///   dart pub global activate flutterfire_cli
///   flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace all placeholder values with output from `flutterfire configure`.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbXTS5Z0IvYWcdA709HMAGk3VRzBoW-lk',
    appId: '1:167886776192:web:1b96396d9c263a829c4365',
    messagingSenderId: '167886776192',
    projectId: 'job-tracker-1f733',
    authDomain: 'job-tracker-1f733.firebaseapp.com',
    storageBucket: 'job-tracker-1f733.firebasestorage.app',
    measurementId: 'G-3ZRDPVW4Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbvrlKZpzR-S97QqZhIcbj04MRIPlMb24',
    appId: '1:167886776192:android:b2b9292d6b3b8fe09c4365',
    messagingSenderId: '167886776192',
    projectId: 'job-tracker-1f733',
    storageBucket: 'job-tracker-1f733.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf_ojQfuFkPD0Tc-eXeczuc3sQgpl0nF4',
    appId: '1:167886776192:ios:566bd4ec24484ec29c4365',
    messagingSenderId: '167886776192',
    projectId: 'job-tracker-1f733',
    storageBucket: 'job-tracker-1f733.firebasestorage.app',
    androidClientId:
        '167886776192-6d2phcaqn2j2tam9p3osiem2rh470ktr.apps.googleusercontent.com',
    iosClientId:
        '167886776192-01qce01423njn39buni746h3h0ubvu60.apps.googleusercontent.com',
    iosBundleId: 'com.jobtracker.jobTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.appspot.com',
    iosBundleId: 'com.jobtracker.jobTracker',
  );

  static bool get isConfigured =>
      currentPlatform.apiKey != 'REPLACE_ME' &&
      currentPlatform.projectId != 'REPLACE_ME';
}
