"""Application activity types."""

from enum import StrEnum


class ActivityType(StrEnum):
    APPLICATION_CREATED = "APPLICATION_CREATED"
    STATUS_CHANGED = "STATUS_CHANGED"
    INTERVIEW_CREATED = "INTERVIEW_CREATED"
    INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED"
    FOLLOWUP_CREATED = "FOLLOWUP_CREATED"
    FOLLOWUP_COMPLETED = "FOLLOWUP_COMPLETED"
    APPLICATION_UPDATED = "APPLICATION_UPDATED"
    GMAIL_EMAIL_RECEIVED = "GMAIL_EMAIL_RECEIVED"
    GMAIL_EMAIL_MATCHED = "GMAIL_EMAIL_MATCHED"
    GMAIL_STATUS_SUGGESTION = "GMAIL_STATUS_SUGGESTION"
    INTERVIEW_SUGGESTION = "INTERVIEW_SUGGESTION"
