"""Email category enumeration for job-related Gmail detection."""

from enum import StrEnum


class EmailCategory(StrEnum):
    APPLICATION_RECEIVED = "APPLICATION_RECEIVED"
    APPLICATION_ACKNOWLEDGED = "APPLICATION_ACKNOWLEDGED"
    SHORTLISTED = "SHORTLISTED"
    HR_CONTACT = "HR_CONTACT"
    HR_INTERVIEW = "HR_INTERVIEW"
    TECHNICAL_INTERVIEW = "TECHNICAL_INTERVIEW"
    CODING_TEST = "CODING_TEST"
    SYSTEM_DESIGN = "SYSTEM_DESIGN"
    MANAGER_INTERVIEW = "MANAGER_INTERVIEW"
    FINAL_INTERVIEW = "FINAL_INTERVIEW"
    OFFER = "OFFER"
    REJECTION = "REJECTION"
    WITHDRAWAL = "WITHDRAWAL"
    ASSESSMENT = "ASSESSMENT"
    FOLLOW_UP = "FOLLOW_UP"
    OTHER_JOB_RELATED = "OTHER_JOB_RELATED"
    NOT_JOB_RELATED = "NOT_JOB_RELATED"
