"""Interview type enumeration."""

from enum import StrEnum


class InterviewType(StrEnum):
    PHONE_SCREEN = "PHONE_SCREEN"
    HR_INTERVIEW = "HR_INTERVIEW"
    TECHNICAL_INTERVIEW = "TECHNICAL_INTERVIEW"
    CODING_TEST = "CODING_TEST"
    SYSTEM_DESIGN = "SYSTEM_DESIGN"
    MANAGER_INTERVIEW = "MANAGER_INTERVIEW"
    FINAL_INTERVIEW = "FINAL_INTERVIEW"
    OTHER = "OTHER"
