"""Notification type enumeration."""

from enum import StrEnum


class NotificationType(StrEnum):
    INTERVIEW_REMINDER = "INTERVIEW_REMINDER"
    FOLLOWUP_REMINDER = "FOLLOWUP_REMINDER"
    FOLLOWUP_OVERDUE = "FOLLOWUP_OVERDUE"
    GMAIL_EMAIL_DETECTED = "GMAIL_EMAIL_DETECTED"
    APPLICATION_STATUS_SUGGESTION = "APPLICATION_STATUS_SUGGESTION"
    INTERVIEW_DETECTED = "INTERVIEW_DETECTED"
    NEW_APPLICATION_DETECTED = "NEW_APPLICATION_DETECTED"
    SYSTEM = "SYSTEM"
